# This allows drone to build the image as per info from the Github webhook
kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world

# This allows publishing the image as long as previous steps were built successfully to an image registry in AWS
# Requires AWS ECR plugin as explained here: http://plugins.drone.io/drone-plugins/drone-ecr/
#- name: publish  
#  image: plugins/ecr
#  settings:
#    access_key:
#      from_secret: aws_access_key_id
#    secret_key:
#      from_secret: aws_secret_access_key
#    create_repository: true
#    repo: bar
#    registry: <account_id>.dkr.ecr.JAKI_REGION.amazonaws.com
#    region: NASZ_REGION
